### ISSUE TITLE
error accessing gitlab-api: null

### ISSUE THREAD

**Issue by luisbrandao** [Argelbargel/gitlab-branch-source-plugin#43] opened 2017-10-03 21:24 UTC
Out of the blue, jenkins stopped building all my gitlab repos.
The repository scan still works, but any build will throw the following error when trying to start:

```
Branch indexing
retrieving head-revision for master
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:330)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:144)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:116)
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranch(GitLabAPI.java:90)
Caused: argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPIException: error accessing gitlab-api: null
	at argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabAPI.getBranch(GitLabAPI.java:94)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveBranchRevision(SourceHeads.java:102)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieveRevision(SourceHeads.java:90)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceHeads.retrieve(SourceHeads.java:77)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource.retrieve(GitLabSCMSource.java:254)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:564)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:95)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:263)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Finished: FAILURE
```

I'm not even sure how to begin debugging this... Maybe some other dependency got updated and broke this plug-in... Can anyone help me with any pointers?

**Comment by rsotnychenko** [comment] 2017-10-05 16:34
Got the same problem and managed to find a workaround.

So the problem is that sometimes the plugin makes request to GitLab with extra slashes, eg.
`GET /api/v3/projects/1234567/repository/branches//master`

About a month ago, GitLab was ignoring this and replying with actual information. After some recent update they started to reply with a redirect to a correct URL. For some reasons the plugin does not handle this redirect and fails.



The workaround is simple:
1. In file _GitLabAPI_.java after line _89_ add the following line:
`tailUrl = tailUrl.replaceAll("//", "/");`
2. Compile, package and upload _.hpi_ artifact to your Jenkins

**Comment by Argelbargel** [comment] 2017-10-05 20:00
Hi @rtsotnychenko, great, think for finding this! If you'll Creme a Pullover Requisiten for this i'll merge and release it asap.

**Comment by Argelbargel** [comment] 2017-10-06 11:02
@rsotnychenko: you're right of course, it'll just be a workaround. as it'll fix the symptoms for people upgrading to gitlab 10 right now. it's okay for me to release ist quickly and look for the root-cause later.

**Comment by Argelbargel** [comment] 2017-10-06 12:22
Workaround is released in 0.6.5.1

**Closed by Argelbargel** 2017-10-06 12:22 UTC

**Comment by luisbrandao** [comment] 2017-10-06 16:15
Fantastic, this really fixed it! 
Many thanx!

**Comment by ilushka85** [comment] 2018-04-16 16:47
this is not fixed in the latest version
