### ISSUE TITLE
Scan failing due to serialization problem

### ISSUE THREAD

**Issue by hibes** [Argelbargel/gitlab-branch-source-plugin#52] opened 2018-01-21 08:26 UTC
Not sure what is going on here.  The scan isn't working, so it never builds the group info.

```
Started by user 
[Sun Jan 21 08:22:23 UTC 2018] Starting organization scan...
[Sun Jan 21 08:22:23 UTC 2018] Updating actions...
[Sun Jan 21 08:22:23 UTC 2018] Consulting GitLab Projects
Retrieving projects for Gitlab.com...
Visiting project group-name/project-name...
Retrieving heads for project group-name/project-name...
Retrieving merge requests...
Retrieving branches...
Monitoring branch master
      ‘Jenkinsfile’ found
master (ce9526b6bc06938ecb7105702f8f0dd88c55194a) meets criteria
Retrieving tags...
error retrieving projects for Gitlab.com: java.io.IOException: java.lang.RuntimeException: Failed to serialize jenkins.branch.MultiBranchProject#sources for class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject
ERROR: [Sun Jan 21 08:22:24 UTC 2018] Could not fetch sources from navigator argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator@6f2c2241
java.lang.UnsupportedOperationException: Refusing to marshal org.gitlab.api.models.GitlabNamespace for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:530)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
Caused: java.lang.RuntimeException: Failed to serialize org.gitlab.api.models.GitlabProject#namespace for class argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabProject
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
Caused: java.lang.RuntimeException: Failed to serialize argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource#project for class argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
Caused: java.lang.RuntimeException: Failed to serialize jenkins.branch.BranchSource#source for class jenkins.branch.BranchSource
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at hudson.util.CopyOnWriteList$ConverterImpl.marshal(CopyOnWriteList.java:187)
	at hudson.util.XStream2$AssociatedConverterImpl.marshal(XStream2.java:448)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
Caused: java.lang.RuntimeException: Failed to serialize hudson.util.PersistedList#data for class jenkins.branch.MultiBranchProject$BranchSourceList
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
Caused: java.lang.RuntimeException: Failed to serialize jenkins.branch.MultiBranchProject#sources for class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:194)
Caused: java.io.IOException
	at hudson.XmlFile.write(XmlFile.java:201)
	at hudson.model.AbstractItem.save(AbstractItem.java:483)
	at com.cloudbees.hudson.plugins.folder.AbstractFolder.save(AbstractFolder.java:1301)
	at hudson.BulkChange.commit(BulkChange.java:98)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1434)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitProject(SourceVisitor.java:65)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:34)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:25)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:133)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:459)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:911)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Sun Jan 21 08:22:24 UTC 2018] Finished organization scan. Scan took 1.4 sec
FATAL: Failed to recompute children of test-gitlab
java.io.IOException: java.lang.RuntimeException: Failed to serialize jenkins.branch.MultiBranchProject#sources for class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject
	at hudson.XmlFile.write(XmlFile.java:201)
	at hudson.model.AbstractItem.save(AbstractItem.java:483)
	at com.cloudbees.hudson.plugins.folder.AbstractFolder.save(AbstractFolder.java:1301)
	at hudson.BulkChange.commit(BulkChange.java:98)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1434)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitProject(SourceVisitor.java:65)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:34)
	at argelbargel.jenkins.plugins.gitlab_branch_source.SourceVisitor.visitSources(SourceVisitor.java:25)
	at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMNavigator.visitSources(GitLabSCMNavigator.java:133)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:459)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:911)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.lang.RuntimeException: Failed to serialize jenkins.branch.MultiBranchProject#sources for class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:194)
	... 14 more
Caused by: java.lang.RuntimeException: Failed to serialize hudson.util.PersistedList#data for class jenkins.branch.MultiBranchProject$BranchSourceList
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 27 more
Caused by: java.lang.RuntimeException: Failed to serialize jenkins.branch.BranchSource#source for class jenkins.branch.BranchSource
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at hudson.util.CopyOnWriteList$ConverterImpl.marshal(CopyOnWriteList.java:187)
	at hudson.util.XStream2$AssociatedConverterImpl.marshal(XStream2.java:448)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 36 more
Caused by: java.lang.RuntimeException: Failed to serialize argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource#project for class argelbargel.jenkins.plugins.gitlab_branch_source.GitLabSCMSource
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 52 more
Caused by: java.lang.RuntimeException: Failed to serialize org.gitlab.api.models.GitlabProject#namespace for class argelbargel.jenkins.plugins.gitlab_branch_source.api.GitLabProject
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 61 more
Caused by: java.lang.UnsupportedOperationException: Refusing to marshal org.gitlab.api.models.GitlabNamespace for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:530)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
	... 70 more
Finished: FAILURE
```

**Comment by martiwi** [comment] 2018-02-11 09:56
Same problem, if it can help, here the plugin version I use:

- branch-api ~~2.0.9~~ -> 2.0.18
- cloudbees-folder ~~6.0.4~~  -> 6.3
- credentials ~~2.1.13~~  -> 2.1.16
- git ~~3.3.0~~  -> 3.7.0
- git-client ~~2.4.5~~  -> 2.7.1
- gitlab-plugin ~~1.4.5~~  -> 1.5.3
- scm-api ~~2.1.1~~  -> 2.2.6
- workflow-api ~~2.13~~  -> 2.25
- workflow-cps ~~2.30~~  -> 2.44
- workflow-job ~~2.11~~  -> 2.17
- workflow-multibranch ~~2.14~~  -> 2.17

**Comment by ananace** [comment] 2018-02-12 13:18
This is due to [JEP-200](https://jenkins.io/blog/2018/01/13/jep-200/) as of Jenkins 2.102
It could probably be worked around by finding all of the classes that attempt serialization and adding them to the whitelist.

As described in their blog entry; `-Dhudson.remoting.ClassFilter=some.pkg.and.ClassName,some.pkg.and.OtherClassName`

**Comment by martiwi** [comment] 2018-02-12 21:59
Indeed working with the following classes:
```
-Dhudson.remoting.ClassFilter=org.gitlab.api.models.GitlabNamespace,org.gitlab.api.models.GitlabPermission,org.gitlab.api.models.GitlabProjectAccessLevel
```
Any plan to have it working without?

**Comment by Argelbargel** [comment] 2018-02-14 01:30
Seems simple enough to fix by providing a ClassFilter file. I'll try to look into it but as you guy might have sorely noticed, i'm a bit busy now with other work. I'll see what i can do...

**Comment by frznlogic** [comment] 2018-03-22 11:41
Hi, experiencing the same issue since a day or two ago, the ClassFilter mentioned by @martiwi isn't enough though for me, not sure if I'm doing something incorrect right now though. 

@Argelbargel I'm not sure how to do that in a ClassFilter file, I tried adding a file like this: src/main/resources/hudson.remoting.ClassFilter with this content:

```
org.gitlab.api.models.GitlabNamespace
org.gitlab.api.models.GitlabPermission
org.gitlab.api.models.GitlabProjectAccessLevel

```
Compiled, installed the plugin but it's not working for me... any ideas what else might need to be done?

**Comment by frznlogic** [comment] 2018-03-22 11:44
I created #57 which is probably a duplicate of this issue to add my error output. Please close as duplicate if it's nothing new ;).

**Comment by grfullerton** [comment] 2018-03-23 15:27
@frznlogic I've got a PR open that should work.  Your changes didnt work because the ClassFilter should have been in `src/main/resources/META-INF/hudson.remoting.ClassFilter`, you forgot the `META-INF` folder.

**Closed** 2018-03-23 16:48 UTC
